AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 13: Final Global Route 53 - Active-Active with Parent Health Checks'

Parameters:
  Region1SecretArn:
    Type: String
    Default: "arn:aws:secretsmanager:us-east-1:327982942129:secret:DCT-us-east-1-INFRA-METADATA-WcRNid"
  Region2SecretArn:
    Type: String
    Default: "arn:aws:secretsmanager:us-east-1:327982942129:secret:DCT-us-east-2-INFRA-METADATA-xIOrdj"

Resources:
  # ==========================================
  # 1. HOSTED ZONE
  # ==========================================
  MyHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: "lets.testwitha.click"

  # ==========================================
  # 2. VIRGINIA HEALTH CHECKS (VA)
  # ==========================================
  # VA - API Check
  Region1APIHC:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        FullyQualifiedDomainName: !Join [ ":", [ "{{resolve:secretsmanager", !Ref Region1SecretArn, "SecretString:HCHost}}" ] ]
        Port: 443
        ResourcePath: "/prod/health"
  
  # VA - ALB Check
  Region1ALBHC:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTP
        FullyQualifiedDomainName: !Join [ ":", [ "{{resolve:secretsmanager", !Ref Region1SecretArn, "SecretString:AlbDns}}" ] ]
        Port: 80
        ResourcePath: "/"

  # VA - PARENT (Calculated)
  Region1ParentHC:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: CALCULATED
        ChildHealthChecks:
          - !Ref Region1APIHC
          - !Ref Region1ALBHC
        HealthThreshold: 2 # Both must be healthy
      HealthCheckTags:
        - Key: Name
          Value: "DCT-VA-PARENT-HEALTH"

  # ==========================================
  # 3. OHIO HEALTH CHECKS (OH)
  # ==========================================
  # OH - API Check
  Region2APIHC:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTPS
        FullyQualifiedDomainName: !Join [ ":", [ "{{resolve:secretsmanager", !Ref Region2SecretArn, "SecretString:HCHost}}" ] ]
        Port: 443
        ResourcePath: "/prod/health"

  # OH - ALB Check
  Region2ALBHC:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: HTTP
        FullyQualifiedDomainName: !Join [ ":", [ "{{resolve:secretsmanager", !Ref Region2SecretArn, "SecretString:AlbDns}}" ] ]
        Port: 80
        ResourcePath: "/"

  # OH - PARENT (Calculated)
  Region2ParentHC:
    Type: AWS::Route53::HealthCheck
    Properties:
      HealthCheckConfig:
        Type: CALCULATED
        ChildHealthChecks:
          - !Ref Region2APIHC
          - !Ref Region2ALBHC
        HealthThreshold: 2 # Both must be healthy
      HealthCheckTags:
        - Key: Name
          Value: "DCT-OH-PARENT-HEALTH"

  # ==========================================
  # 4. WEIGHTED DNS RECORDS (Referencing Parent HCs)
  # ==========================================
  VirginiaWeightedRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref MyHostedZone
      Name: "api.lets.testwitha.click"
      Type: CNAME
      TTL: 60
      SetIdentifier: "VA-PRIMARY"
      Weight: 50
      ResourceRecords:
        - !Join [ ":", [ "{{resolve:secretsmanager", !Ref Region1SecretArn, "SecretString:AlbDns}}" ] ]
      HealthCheckId: !Ref Region1ParentHC

  OhioWeightedRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref MyHostedZone
      Name: "api.lets.testwitha.click"
      Type: CNAME
      TTL: 60
      SetIdentifier: "OH-PRIMARY"
      Weight: 50
      ResourceRecords:
        - !Join [ ":", [ "{{resolve:secretsmanager", !Ref Region2SecretArn, "SecretString:AlbDns}}" ] ]
      HealthCheckId: !Ref Region2ParentHC