AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 12: Global Metadata Secret - Centralizing Steps 1-11 Infrastructure Data'

Resources:
  # This secret captures every regional and global export for simplified management
  InfraMetadataSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "DCT-${AWS::Region}-INFRA-METADATA"
      Description: !Sub "Aggregated infrastructure metadata for ${AWS::Region}"
      SecretString:
        Fn::Sub:
          - |
            {
              "Networking": {
                "VpcId": "${VpcId}",
                "PublicSubnets": "${PubSubs}",
                "PrivateSubnets": "${PrivSubs}",
                "IGW": "${Igw}",
                "NAT": "${Nat}",
                "EIP": "${Eip}"
              },
              "Security": {
                "SGs": {
                  "ALB": "${AlbSg}",
                  "Web": "${WebSg}",
                  "Database": "${DbSg}",
                  "Aurora": "${AuroraSg}",
                  "Lambda": "${LambdaSg}"
                }
              },
              "Endpoints": {
                "SecretsVPCE": "${SecretsVpce}",
                "ApiVPCE": "${ApiVpce}",
                "EIC": "${Eic}"
              },
              "Database": {
                "GlobalClusterId": "${GlobalDbId}",
                "RegionalEndpoint": "${DbEndpoint}",
                "SecretArn": "${DbSecretArn}"
              },
              "Application": {
                "ApiUrl": "${ApiUrl}",
                "HealthCheckUrl": "${HcUrl}",
                "AlbDns": "${AlbDns}",
                "AsgName": "${AsgName}"
              }
            }
          - VpcId: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-VPC-ID" }
            PubSubs: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-PUB-SUBS" }
            PrivSubs: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-PRIV-SUBS" }
            Igw: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-IGW-ID" }
            Nat: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-NGW-ID" }
            Eip: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-NAT-EIP" }
            AlbSg: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-ALB-SG" }
            WebSg: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-EC2-WEB-SG" }
            DbSg: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-EC2-DB-SG" }
            AuroraSg: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-AURORA-SG" }
            LambdaSg: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-LAMBDA-SG" }
            SecretsVpce: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-VPCE-SECRETS-ID" }
            ApiVpce: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-VPCE-API-ID" }
            Eic: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-EIC-ENDPOINT-ID" }
            GlobalDbId: { "Fn::ImportValue": "GLOBAL-DB-IDENTIFIER" }
            DbEndpoint: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-DB-ENDPOINT" }
            DbSecretArn: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-AURORA-SECRET-ARN" }
            ApiUrl: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-API-URL" }
            HcUrl: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-HC-URL" }
            AlbDns: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-ALB-DNS" }
            AsgName: { "Fn::ImportValue": !Sub "REGION-${AWS::Region}-ASG-NAME" }

Outputs:
  MetadataSecretArn:
    Value: !Ref InfraMetadataSecret
    Export:
      Name: !Sub "REGION-${AWS::Region}-METADATA-SECRET-ARN"