AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 14: Final Hardened Aurora Failover - Production Logic'

Parameters:
  AlertEmail:
    Type: String
    Default: "aniket.gangwar.92@gmail.com"
  GlobalDbId:
    Type: String
    Default: "dct-global-database"

Resources:
  # 1. SNS TOPIC (Central Alert Hub)
  FailoverSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DCT-GLOBAL-FAILOVER-ALERTS"
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail
        - Protocol: lambda
          Endpoint: !GetAtt FailoverFunction.Arn

  # 2. IAM ROLE (Hardened Least Privilege)
  FailoverLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RDSFailoverPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:FailoverGlobalCluster
                  - rds:DescribeGlobalClusters
                Resource: 
                  - !Sub "arn:aws:rds::${AWS::AccountId}:global-cluster:${GlobalDbId}"
                  - "arn:aws:rds:us-east-2:327982942129:cluster:dct-us-east-2-aurora*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DCT-GLOBAL-FAILOVER-ALERTS"

  # 3. LAMBDA FUNCTION (With Loop Protection & Writer Check)
  FailoverFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "DCT-Aurora-Global-Failover"
      Handler: "index.lambda_handler"
      Role: !GetAtt FailoverLambdaRole.Arn
      Runtime: python3.9
      Timeout: 120 
      Environment:
        Variables:
          GLOBAL_DB_ID: !Ref GlobalDbId
          TARGET_CLUSTER_ARN: "arn:aws:rds:us-east-2:327982942129:cluster:dct-us-east-2-aurora"
          TOPIC_NAME: "DCT-GLOBAL-FAILOVER-ALERTS"
      Code:
        ZipFile: |
          import boto3
          import os

          GLOBAL_DB_ID = os.environ.get('GLOBAL_DB_ID')
          TARGET_CLUSTER_ARN = os.environ.get('TARGET_CLUSTER_ARN')
          TOPIC_NAME = os.environ.get('TOPIC_NAME')
          
          rds = boto3.client('rds')
          sns = boto3.client('sns')

          def lambda_handler(event, context):
              region = context.invoked_function_arn.split(':')[3]
              account_id = context.invoked_function_arn.split(':')[4]
              sns_topic_arn = f"arn:aws:sns:{region}:{account_id}:{TOPIC_NAME}"

              try:
                  # Describe global cluster to check status and current writer
                  response = rds.describe_global_clusters(GlobalClusterIdentifier=GLOBAL_DB_ID)
                  global_cluster = response['GlobalClusters'][0]
                  
                  if global_cluster['Status'] != 'available':
                      print(f"⚠️ Skipping: Cluster {GLOBAL_DB_ID} is {global_cluster['Status']}")
                      return {"status": "skipped"}

                  # Logic Check: Is our target already the primary?
                  current_primary = ""
                  for member in global_cluster['GlobalClusterMembers']:
                      if member['IsWriter']:
                          current_primary = member['DBClusterArn']

                  if current_primary == TARGET_CLUSTER_ARN:
                      print(f"✅ {TARGET_CLUSTER_ARN} is already the Primary. No action taken.")
                      return {"status": "no_action_required"}

                  print(f"🚀 Promoting {TARGET_CLUSTER_ARN} to Primary...")
                  rds.failover_global_cluster(
                      GlobalClusterIdentifier=GLOBAL_DB_ID,
                      TargetDbClusterIdentifier=TARGET_CLUSTER_ARN
                  )
                  return {"status": "success"}

              except Exception as e:
                  error_msg = str(e)
                  print(f"❌ Error: {error_msg}")
                  
                  # STOP THE BOMBARDMENT: Suppress SNS for Rate Limits or "Already Primary" errors
                  suppress_errors = ["Rate exceeded", "InvalidParameterCombination"]
                  if not any(err in error_msg for err in suppress_errors):
                      sns.publish(
                          TopicArn=sns_topic_arn, 
                          Message=f"❌ Failover API Failed for {GLOBAL_DB_ID}: {error_msg}", 
                          Subject="CRITICAL: Failover Automation Error"
                      )
                  raise e

  # 4. PERMISSIONS (SNS to Lambda)
  SNSInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref FailoverFunction
      Principal: "sns.amazonaws.com"
      SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DCT-GLOBAL-FAILOVER-ALERTS"

  # 5. CLOUDWATCH ALARM (The Primary Trigger)
  Region1FailoverAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "DCT-REGION1-CRITICAL-FAILOVER"
      AlarmDescription: "Monitors Virginia Health; Triggers SNS for Alerts/Failover"
      MetricName: "HealthCheckStatus"
      Namespace: "AWS/Route53"
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: { "Fn::ImportValue": "REGION-us-east-1-PARENT-HC-ID" }
      AlarmActions:
        - !Ref FailoverSNSTopic