AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 6.1: Secrets Manager for Aurora Global Database (Virginia) - Full Package'

Resources:
  # 1. The Database Secret
  AuroraSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "dct-us-east-1-aurora-secret"
      Description: "Full connection credentials for the Aurora Global Database"
      # FIXED: Added host, port, and engine to the secret package
      SecretString: 
        Fn::Sub: 
          - '{"username":"admin","password":"YourSecurePassword123!","host":"${DBEndpoint}","port":"3306","engine":"mysql"}'
          - DBEndpoint: 
              Fn::ImportValue: !Sub "REGION-${AWS::Region}-DB-ENDPOINT"
      Tags:
        - Key: Project
          Value: "DCT-Active-Active"

Outputs:
  SecretArn:
    Value: !Ref AuroraSecret
    Export:
      Name: 
        Fn::Sub: "REGION-${AWS::Region}-AURORA-SECRET-ARN"

  SecretName:
    Value: !Ref AuroraSecret
    Export:
      Name: 
        Fn::Sub: "REGION-${AWS::Region}-AURORA-SECRET-NAME"