AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 6.1: Secrets Manager for Aurora Global Database (Virginia) - Fixed'

Resources:
  # 1. The Database Secret
  AuroraSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      # Explicit name for easy discovery
      Name: "dct-us-east-1-aurora-secret"
      Description: "Credentials for the Aurora Global Database"
      # IMPORTANT: Ensure this matches your Step 6 password
      SecretString: !Sub '{"username":"admin","password":"YourSecurePassword123!"}'
      Tags:
        - Key: Project
          Value: "DCT-Active-Active"

Outputs:
  SecretArn:
    Description: "The ARN of the Aurora Secret"
    # !Ref on a Secret returns the ARN
    Value: !Ref AuroraSecret
    Export:
      Name: 
        Fn::Sub: "REGION-${AWS::Region}-AURORA-SECRET-ARN"

  SecretName:
    Description: "The Name of the Aurora Secret"
    # FIXED: Use !Ref to get the name/ID of the secret
    Value: !Ref AuroraSecret
    Export:
      Name: 
        Fn::Sub: "REGION-${AWS::Region}-AURORA-SECRET-NAME"