AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 7: Automated Regional Database Schema Initialization (Ubuntu) - Fixed'

Resources:
  DBManagerInstance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M 
        Count: 1
    Properties:
      ImageId: 
        Fn::ImportValue: !Sub "REGION-${AWS::Region}-AMI"
      InstanceType: t4g.micro 
      SubnetId: 
        Fn::Select: 
          - 0
          - Fn::Split: 
              - ","
              - Fn::ImportValue: !Sub "REGION-${AWS::Region}-PRIV-SUBS"
      IamInstanceProfile: 
        Fn::ImportValue: "GLOBAL-MGMT-PROFILE"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "REGION-${AWS::Region}-EC2-DB-SG"
      Tags:
        - Key: Name
          Value: !Sub "DCT-${AWS::Region}-DB-MANAGER"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Redirect output to log for debugging via SSH/Instance Connect
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

          # 1. Install CloudFormation Helper Scripts (Required for Ubuntu)
          apt-get update -y
          apt-get install -y python3-pip mysql-client jq awscli
          pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz

          # 2. Wait for Networking
          sleep 30

          # 3. Discovery Logic
          SECRET_NAME="dct-${AWS::Region}-aurora-secret"
          
          # 4. Wait for Database
          echo "Waiting for Aurora..."
          until aws rds describe-db-clusters --db-cluster-identifier "DCT-${AWS::Region}-AURORA" --region ${AWS::Region} --query 'DBClusters[0].Status' --output text | grep -q "available"; do
            sleep 30
          done

          # 5. Extract Credentials
          SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --region ${AWS::Region} --query 'SecretString' --output text)
          DB_HOST=$(echo $SECRET_JSON | jq -r .host)
          DB_PASSWORD=$(echo $SECRET_JSON | jq -r .password)

          # 6. Run SQL
          mysql -h "$DB_HOST" -u admin -p"$DB_PASSWORD" <<EOF
          CREATE DATABASE IF NOT EXISTS dctapp;
          USE dctapp;
          CREATE TABLE IF NOT EXISTS health_check (id INT AUTO_INCREMENT PRIMARY KEY, status VARCHAR(50), last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP);
          INSERT INTO health_check (status) VALUES ('healthy');
          CREATE TABLE IF NOT EXISTS submissions (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) DEFAULT 'Anonymous', message TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
          EOF

          # 7. Signal Success using the newly installed cfn-signal
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource DBManagerInstance --region ${AWS::Region}

Outputs:
  ManagerInstanceId:
    Value: !Ref DBManagerInstance
    Export:
      Name: !Sub "REGION-${AWS::Region}-DB-MANAGER-ID"