AWSTemplateFormatVersion: '2010-09-09'
Description: 'Step 14: Final Hardened Aurora Failover - Throttling & Case Fix'

Parameters:
  AlertEmail:
    Type: String
    Default: "aniket.gangwar.92@gmail.com"
  GlobalDbId:
    Type: String
    Default: "dct-global-database"

Resources:
  FailoverSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: "DCT-GLOBAL-FAILOVER-ALERTS"
      Subscription:
        - Protocol: email
          Endpoint: !Ref AlertEmail
        - Protocol: lambda
          Endpoint: !GetAtt FailoverFunction.Arn

  FailoverLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: RDSFailoverPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - rds:FailoverGlobalCluster
                  - rds:DescribeGlobalClusters
                Resource: 
                  - !Sub "arn:aws:rds::${AWS::AccountId}:global-cluster:${GlobalDbId}"
                  - "arn:aws:rds:us-east-2:327982942129:cluster:dct-us-east-2-aurora*"
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DCT-GLOBAL-FAILOVER-ALERTS"

  FailoverFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: "DCT-Aurora-Global-Failover"
      Handler: "index.lambda_handler"
      Role: !GetAtt FailoverLambdaRole.Arn
      Runtime: python3.9
      Timeout: 120 
      Environment:
        Variables:
          GLOBAL_DB_ID: !Ref GlobalDbId
          TARGET_CLUSTER_ARN: "arn:aws:rds:us-east-2:327982942129:cluster:dct-us-east-2-aurora"
          TOPIC_NAME: "DCT-GLOBAL-FAILOVER-ALERTS"
      Code:
        ZipFile: |
          import boto3
          import os
          GLOBAL_DB_ID = os.environ.get('GLOBAL_DB_ID')
          TARGET_CLUSTER_ARN = os.environ.get('TARGET_CLUSTER_ARN')
          TOPIC_NAME = os.environ.get('TOPIC_NAME')
          rds = boto3.client('rds')
          sns = boto3.client('sns')
          def lambda_handler(event, context):
              region = context.invoked_function_arn.split(':')[3]
              account_id = context.invoked_function_arn.split(':')[4]
              sns_topic_arn = f"arn:aws:sns:{region}:{account_id}:{TOPIC_NAME}"
              try:
                  clusters = rds.describe_global_clusters(GlobalClusterIdentifier=GLOBAL_DB_ID)
                  status = clusters['GlobalClusters'][0]['Status']
                  if status != 'available':
                      print(f"⚠️ Skipping: Cluster {GLOBAL_DB_ID} is {status}")
                      return {"status": "skipped"}
                  print(f"🚀 Promoting {TARGET_CLUSTER_ARN}...")
                  rds.failover_global_cluster(
                      GlobalClusterIdentifier=GLOBAL_DB_ID,
                      TargetDbClusterIdentifier=TARGET_CLUSTER_ARN
                  )
                  return {"status": "success"}
              except Exception as e:
                  error_msg = f"❌ Failover API Failed for {GLOBAL_DB_ID}: {str(e)}"
                  print(error_msg)
                  # Only publish if it's NOT a throttling error to prevent loops
                  if "Rate exceeded" not in str(e):
                      sns.publish(TopicArn=sns_topic_arn, Message=error_msg, Subject="CRITICAL: Failover Failed")
                  raise e

  SNSInvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref FailoverFunction
      Principal: "sns.amazonaws.com"
      SourceArn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DCT-GLOBAL-FAILOVER-ALERTS"

  Region1FailoverAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "DCT-REGION1-CRITICAL-FAILOVER"
      AlarmDescription: "Monitors Virginia Health; Triggers SNS for Alerts/Failover"
      MetricName: "HealthCheckStatus"
      Namespace: "AWS/Route53"
      Statistic: Minimum
      Period: 60
      EvaluationPeriods: 2
      Threshold: 1
      ComparisonOperator: LessThanThreshold
      Dimensions:
        - Name: HealthCheckId
          Value: { "Fn::ImportValue": "REGION-us-east-1-PARENT-HC-ID" }
      AlarmActions:
        - !Ref FailoverSNSTopic